version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=512MB"
    ports:
      - "${PORT}:5432"

  web:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  postgres_data: