# Generated by Django 4.1.3 on 2022-11-11 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('end_parse', models.DateField(default=datetime.date(2022, 9, 1))),
                ('group_link', models.CharField(max_length=32, unique=True)),
                ('group_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.faculties')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.programs')),
            ],
        ),
    ]
