# Generated by Django 4.1.3 on 2022-11-11 03:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=128)),
                ('class_audience', models.CharField(max_length=64)),
                ('class_building', models.CharField(max_length=1)),
                ('class_type', models.CharField(max_length=32)),
                ('class_date', models.DateField()),
                ('class_start', models.TimeField()),
                ('class_end', models.TimeField()),
                ('class_teachers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.groups')),
            ],
        ),
    ]
