# Generated by Django 4.1.3 on 2022-11-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.faculties'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.programs'),
        ),
    ]
