# Generated by Django 4.1.3 on 2022-11-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_faculties_options_alter_groups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_parsed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='faculty_name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.faculties'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.programs'),
        ),
    ]
