# Generated by Django 4.1.3 on 2022-11-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_groups_is_parsed_alter_faculties_faculty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='is_parsed',
        ),
    ]
