# Generated by Django 4.1.3 on 2022-11-14 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_classes_class_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_audience',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.groups'),
        ),
    ]
