# Generated by Django 4.1.3 on 2022-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_classes_class_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_building',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
