# Generated by Django 4.1.3 on 2022-11-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_classes_class_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_building',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
