# Generated by Django 4.1.3 on 2022-11-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_classes_class_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='end_parse',
        ),
    ]
